/**
 * REGISTERING THE WORKER THAT MAKES THE APPLICATION OPEN WITH NO NETWORK.
 *
 * The worker itself is generated by the build (`tools/finish-build.mjs`) because its precache
 * list has to name the real emitted filenames. This module only registers it, and only in a real
 * build: during development the worker would serve a stale bundle back at the developer, which is
 * the same failure it exists to prevent, arriving a great deal sooner.
 */

/** The generated worker sits at the site root so its scope covers the whole application. */
const SERVICE_WORKER_PATH = 'sw.js';

export interface OfflineStartOutcome {
  readonly registered: boolean;
  /** Why registration was not attempted or did not succeed; null when it did. */
  readonly reason: string | null;
}

/**
 * Registers the service worker under the application's own base path.
 *
 * Never throws: a browser that refuses the worker still runs the application, it simply does not
 * start offline, and that is reported rather than hidden.
 *
 * @param basePath the path the application is served under, ending in a slash
 */
export async function startOfflineSupport(basePath: string): Promise<OfflineStartOutcome> {
  if (!import.meta.env.PROD) {
    return { registered: false, reason: 'not registered in development, by design' };
  }
  if (!('serviceWorker' in navigator)) {
    return { registered: false, reason: 'this browser has no service worker support' };
  }

  try {
    await navigator.serviceWorker.register(`${basePath}${SERVICE_WORKER_PATH}`, {
      scope: basePath,
      type: 'classic',
    });
    return { registered: true, reason: null };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    console.error('[offline] service worker registration failed; the app will need a network', error);
    return { registered: false, reason };
  }
}
