/**
 * REGISTERING THE WORKER THAT MAKES THE APPLICATION OPEN WITH NO NETWORK.
 *
 * The worker itself is generated by the build (`tools/finish-build.mjs`) because its precache
 * list has to name the real emitted filenames. This module only registers it, and only in a real
 * build: during development the worker would serve a stale bundle back at the developer, which is
 * the same failure it exists to prevent, arriving a great deal sooner.
 */

/** The generated worker sits at the site root so its scope covers the whole application. */
const SERVICE_WORKER_PATH = 'sw.js';

export interface OfflineStartOutcome {
  readonly registered: boolean;
  /** Why registration was not attempted or did not succeed; null when it did. */
  readonly reason: string | null;
}

/**
 * The arriving worker, as narrowly as this module needs it. Structural on purpose: the real
 * `ServiceWorker` satisfies it, and so does a plain object in a test, so the whole decision below is
 * driven without a browser.
 */
export interface ArrivingWorker {
  readonly state: string;
  addEventListener(type: 'statechange', listener: () => void): void;
}

/** The registration, likewise — only the three members this module reads. */
export interface WatchableRegistration {
  readonly installing: ArrivingWorker | null;
  addEventListener(type: 'updatefound', listener: () => void): void;
  /** Ask the browser, once, whether a newer worker exists. See {@link armNewVersionWatch}. */
  update(): Promise<unknown>;
}

/**
 * The document, likewise — only the two members the return check reads. Structural for the same reason
 * as the others: the real `document` satisfies it and so does a plain object in a test.
 */
export interface WatchableDocument {
  readonly visibilityState: string;
  addEventListener(type: 'visibilitychange', listener: () => void): void;
}

/** The container, likewise. `controller` is the fact the whole decision turns on. */
export interface WatchableWorkers {
  readonly controller: object | null;
  addEventListener(type: 'controllerchange', listener: () => void): void;
}

/**
 * TELL ME ONCE, WHEN A NEWER BUILD HAS ARRIVED UNDER A PAGE THAT IS ALREADY RUNNING AN OLDER ONE.
 *
 * ## IT IS ARMED BEFORE THE REGISTRATION EXISTS, AND THAT IS THE WHOLE SHAPE OF THIS FUNCTION
 *
 * It takes the container and returns a function to hand the registration to LATER, rather than taking
 * both at once. That is not indirection for its own sake: `register()` on a first-ever visit ends with
 * this page controlled, so a function taking both at once could only ever read `controller` AFTER the
 * thing that changes it. The fact has to be captured on the near side of that call, and putting the
 * capture in the caller would move the one line this decision rests on out of the module that owns it.
 *
 * ## THE SIGNAL IS NOT `waiting`, AND THAT IS MEASURED RATHER THAN CHOSEN
 *
 * The obvious reading of this problem is "watch for a worker sitting in `waiting`". THAT STATE IS NOT
 * THE SIGNAL HERE, because `sw.js` — generated by `tools/finish-build.mjs` — calls `skipWaiting()` on
 * install and `clients.claim()` on activate, deliberately: an installed home-screen application may
 * never have all its tabs closed, so a worker that waited politely would wait forever. A new worker
 * therefore passes through `waiting` too briefly to be a state anything can rely on seeing.
 *
 * What IS reliable, and what this watches for: **a new worker reached `installed` or `activated` while
 * this page was ALREADY CONTROLLED.** Already controlled means an older build's worker was answering
 * for this document when it started — which is exactly the coach returning to an application he
 * already has, and exactly the case a fresh install cannot reproduce.
 *
 * ## WHY `controller` IS READ BEFORE ANYTHING IS REGISTERED, AND READ ONLY ONCE
 *
 * On a FIRST-EVER visit there is no controller, the worker installs, it claims the page, and the
 * container's `controller` becomes set — so a check made after the fact cannot tell a first install
 * from an update. Reading it at the start and keeping that answer is what makes the first install
 * structurally unable to announce anything, rather than relying on some other condition happening not
 * to hold. `offline-start.test.ts` drives both directions.
 *
 * ## IT ANNOUNCES AT MOST ONCE
 *
 * Both signals below can fire for the same arrival — the worker reaching `installed` and then claiming
 * the page. The coach is being told one thing, so he is told it once.
 *
 * ## ONE CHECK PER RETURN, BECAUSE A LOAD IS NOT WHAT THE COACH DOES
 *
 * The browser checks for a newer worker when the application registers, which is once per document
 * LOAD. `s11/a19` measured what that leaves out: an old build left open through six simulated resumes
 * across sixty seconds was NEVER told, and one real load told it immediately. An installed home-screen
 * application swiped back to issues no navigation, so the load-time check never runs again — and a
 * home-screen application is the only thing the coach has.
 *
 * So `page` is watched for the document becoming visible again, and each return asks the browser once,
 * via `registration.update()`. THE USER RULED THIS AND BOUNDED IT (`d236`, his own words, "Add the check
 * on return"): ONE CHECK PER RETURN. Not a timer, not an interval, not a retry. Nothing in this file
 * arms a clock of any kind, and `offline-start.test.ts` pins that both by counting the calls across real
 * elapsed time and by scanning this source for the timer APIs by name — which is why neither of those
 * names is written out here. A poll would be a DIFFERENT feature from the one he agreed to, and it
 * would fail those tests.
 *
 * Nothing is SHOWN by any of this. A return with no newer build fires no `updatefound`, so `announce`
 * is never reached and the coach sees exactly nothing — which is what almost every return is.
 *
 * @param workers the container the page is controlled by, read for `controller` and `controllerchange`
 * @param announce called at most once, when a newer version is ready for this page to take
 * @param page the document, watched for returns. Omitted — as `offline-start.test.ts` does when it is
 * driving the arrival signals alone — nothing is watched and the load-time check is the only check.
 * @returns the other half: hand it the registration once `register()` has resolved
 */
export function armNewVersionWatch(
  workers: WatchableWorkers,
  announce: () => void,
  page?: WatchableDocument,
): (registration: WatchableRegistration) => void {
  // THE ONE LINE THIS DECISION RESTS ON. Read here, kept, and never re-read.
  const controlledAtStart = workers.controller !== null;
  let announced = false;

  const sayItOnce = () => {
    if (!controlledAtStart || announced) return;
    announced = true;
    announce();
  };

  // The other end of the same arrival: the new worker has claimed this page. The page is STILL running
  // the older build's modules at this moment — they were executed before any of this — which is
  // precisely why he has to be told rather than left to notice.
  workers.addEventListener('controllerchange', sayItOnce);

  return (registration) => {
    // THE CHECK ON RETURN. Armed here rather than above because this is where the registration exists,
    // and it asks for nothing while the document is hidden — a `visibilitychange` fires on the way out
    // as well as on the way in.
    page?.addEventListener('visibilitychange', () => {
      if (page.visibilityState !== 'visible') return;
      void registration.update().catch((error: unknown) => {
        // A failed check shows him nothing and is not retried: he is no worse off than before the
        // return, and a retry is the timer this feature is bounded against.
        console.error('[offline] the check for a newer version failed on return', error);
      });
    });

    registration.addEventListener('updatefound', () => {
      const arriving = registration.installing;
      if (arriving === null) return;

      const look = () => {
        // `activated` as well as `installed`: with skipWaiting the two can be a single turn apart, and
        // a listener attached a moment late would otherwise miss the only edge it was watching for.
        if (arriving.state === 'installed' || arriving.state === 'activated') sayItOnce();
      };
      arriving.addEventListener('statechange', look);
      // Read it immediately too — the worker may already have got there while this ran.
      look();
    });
  };
}

/**
 * Registers the service worker under the application's own base path.
 *
 * Never throws: a browser that refuses the worker still runs the application, it simply does not
 * start offline, and that is reported rather than hidden.
 *
 * @param basePath the path the application is served under, ending in a slash
 * @param whenANewerVersionIsReady called at most once, if a newer build arrives under this running
 * page. Optional: a caller with nowhere to show it registers exactly as before. See
 * {@link armNewVersionWatch} for what "newer build arrives" means and why it is not `waiting`.
 */
export async function startOfflineSupport(
  basePath: string,
  whenANewerVersionIsReady?: () => void,
): Promise<OfflineStartOutcome> {
  if (!import.meta.env.PROD) {
    return { registered: false, reason: 'not registered in development, by design' };
  }
  if (!('serviceWorker' in navigator)) {
    return { registered: false, reason: 'this browser has no service worker support' };
  }

  // ARMED BEFORE REGISTERING, and the order is load-bearing rather than tidy: `register()` on a
  // first-ever visit ends with this page controlled, so "was this page already controlled?" stops
  // being answerable the moment that call is made. See the note on `armNewVersionWatch`.
  const watch =
    whenANewerVersionIsReady === undefined
      ? null
      : armNewVersionWatch(navigator.serviceWorker, whenANewerVersionIsReady, document);

  try {
    const registration = await navigator.serviceWorker.register(`${basePath}${SERVICE_WORKER_PATH}`, {
      scope: basePath,
      type: 'classic',
    });
    if (watch !== null) watch(registration);
    return { registered: true, reason: null };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    console.error('[offline] service worker registration failed; the app will need a network', error);
    return { registered: false, reason };
  }
}
