/**
 * GENERATING AND NORMALISING THE OPTIONAL PASSPHRASE.
 *
 * The phrase is generated by the application, never chosen by the coach, and it doubles as the
 * written recovery code. See `wordlist.js` for why both of those are deliberate.
 *
 * ## Uniform selection, by rejection sampling
 *
 * The word list is not a power of two, so reducing a random value modulo the list length would
 * make the earliest words very slightly more likely than the rest. That bias is small and it
 * is also entirely avoidable: values landing above the largest whole multiple of the list
 * length are DISCARDED and another is drawn. The loop terminates with probability one and in
 * practice almost always on the first draw.
 *
 * It matters because {@link import('./wordlist.js').PHRASE_ENTROPY_BITS} is a number stated in
 * the security notes. A figure computed from a uniform draw is true; the same figure computed
 * from a biased one is an overstatement, and overstating what a control buys is the one thing
 * those notes must never do.
 *
 * ## Normalising on the way back in
 *
 * A phrase written on paper comes back with a stray capital, a double space, or a line break
 * where the pen ran out of room. None of that is a wrong passphrase, and treating it as one
 * would tell the coach he has lost something he is holding in his hand — which, for a recovery
 * code, is about the most damaging false alarm the application could raise. So the phrase is
 * normalised to one canonical form before derivation, both when it is created and when it is
 * entered, and the two therefore always agree.
 */

import { randomBytes } from './primitives.js';
import { PHRASE_ENTROPY_BITS, PHRASE_WORDS, WORDS } from './wordlist.js';
import { CryptoInvalidRequest } from './errors.js';

/**
 * The non-breaking space, written as an escape because it is indistinguishable from an
 * ordinary space on screen. A mobile keyboard inserts one now and then without telling
 * anyone, and a phrase carrying one would otherwise fail to normalise to the form it was
 * generated in — presenting as a wrong recovery code when nothing is wrong at all.
 */
const NON_BREAKING_SPACE = '\u00a0';

/** The separator between words in the canonical form. */
const WORD_SEPARATOR = ' ';

/**
 * One uniformly-chosen index into the word list.
 *
 * Two bytes are drawn at a time because the list is larger than a single byte can address.
 * The ceiling is the largest whole multiple of the list length that fits in sixteen bits;
 * anything at or above it is discarded rather than folded, which is what keeps the draw
 * uniform.
 *
 * @returns {number}
 */
function uniformIndex() {
  const n = WORDS.length;
  const ceiling = Math.floor(65536 / n) * n;
  for (;;) {
    const b = randomBytes(2);
    const value = (b[0] << 8) | b[1];
    if (value < ceiling) return value % n;
  }
}

/**
 * A fresh six-word phrase.
 *
 * Words may repeat. That is not a flaw to be corrected: forbidding repeats would make the
 * draw non-uniform and would REDUCE the entropy while appearing to improve the phrase. The
 * stated bit figure is only true of an unconstrained draw.
 *
 * @param {{words?: number}} [opts]
 * @returns {{phrase: string, words: string[], entropyBits: number}}
 */
export function generatePassphrase(opts = {}) {
  const count = opts.words ?? PHRASE_WORDS;
  if (!Number.isInteger(count) || count < 1) {
    throw new CryptoInvalidRequest('A passphrase needs a positive whole number of words.');
  }
  const words = [];
  for (let i = 0; i < count; i += 1) words.push(WORDS[uniformIndex()]);
  return {
    phrase: words.join(WORD_SEPARATOR),
    words,
    entropyBits: count === PHRASE_WORDS
      ? PHRASE_ENTROPY_BITS
      : Math.log2(WORDS.length) * count,
  };
}

/**
 * The canonical form of a phrase as typed back in.
 *
 * Lower-cased, trimmed, and every run of whitespace — spaces, tabs, the line break where the
 * writing wrapped — collapsed to a single space. Nothing else is changed: a word that is
 * genuinely wrong stays wrong, because silently correcting a near-miss would mean the
 * application deciding what the coach meant to write.
 *
 * @param {string} phrase
 * @returns {string}
 */
export function normalizePassphrase(phrase) {
  if (typeof phrase !== 'string') {
    throw new CryptoInvalidRequest('A passphrase must be text.');
  }
  const words = [];
  let current = '';
  for (const ch of phrase.toLowerCase()) {
    if (isWhitespace(ch)) {
      if (current !== '') { words.push(current); current = ''; }
    } else {
      current += ch;
    }
  }
  if (current !== '') words.push(current);
  return words.join(WORD_SEPARATOR);
}

/**
 * Whitespace, enumerated rather than matched.
 *
 * The characters a phrase written on paper and typed back in can actually pick up: a space, a
 * tab, the two halves of a line break, and the non-breaking space a mobile keyboard sometimes
 * inserts without telling anyone.
 *
 * @param {string} ch
 * @returns {boolean}
 */
function isWhitespace(ch) {
  return ch === ' ' || ch === '\t' || ch === '\n' || ch === '\r' || ch === NON_BREAKING_SPACE;
}

/**
 * Every word of this phrase that is not in the list.
 *
 * Offered so the interface can point at the word that went wrong when the coach types his
 * phrase back in — "the fourth word is not one we use" is actionable, whereas "that did not
 * work" sends someone hunting through six words with no idea which one to look at. It is a
 * HELP, never a gate: a phrase is accepted or rejected by whether it opens the slot, and
 * nothing here is allowed to refuse one that would have worked.
 *
 * @param {string} phrase
 * @returns {{index: number, word: string}[]}
 */
export function unknownWords(phrase) {
  const known = new Set(WORDS);
  return normalizePassphrase(phrase)
    .split(WORD_SEPARATOR)
    .map((word, index) => ({ index, word }))
    .filter(({ word }) => word !== '' && !known.has(word));
}

export { PHRASE_ENTROPY_BITS, PHRASE_WORDS };
