/**
 * POST-BUILD: write the build record, then generate the service worker around it.
 *
 * This runs immediately after `vite build`, as the second half of `npm run build`. It exists
 * because both things it produces need to know the ACTUAL emitted filenames, which are content
 * hashed and therefore unknown until the bundler has finished.
 *
 * The output directory it writes into is named ONCE, in `tools/build-config.mjs`, and read from
 * there — the publish step will have to move that output, and a directory hardcoded across four
 * files is how a build ends up writing a correct artefact somewhere nothing serves.
 *
 * It writes two files into the output directory:
 *
 * 1. `build-info.json` — the build record. Its `sourceStamp` is the marker that makes a stale
 *    committed artefact detectable; see `tools/source-stamp.mjs` for why that matters and
 *    `tools/check-stale.mjs` for the check itself.
 * 2. `sw.js` — the service worker, with the precache list written into it. The list is the real
 *    emitted file names rather than a guess, which is the only way a precache can be complete.
 *
 * Both are committed along with the rest of `dist/`.
 */

import { readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { BASE_PATH, BUNDLER_MANIFEST_FILE, OUTPUT_DIRECTORY } from './build-config.mjs';
import { applicationRoot, computeSourceStamp } from './source-stamp.mjs';

const BUILD_INFO_FILE = 'build-info.json';
const SERVICE_WORKER_FILE = 'sw.js';

/** Emitted files that must never be precached by the worker that serves them. */
const NEVER_PRECACHED = Object.freeze([SERVICE_WORKER_FILE]);

/**
 * Every emitted file under the output directory, as POSIX paths relative to it.
 *
 * @param {string} outputDirectory
 * @returns {Promise<string[]>}
 */
async function listEmittedFiles(outputDirectory) {
  const found = [];

  const walk = async (relativeDirectory) => {
    const absolute = relativeDirectory
      ? path.join(outputDirectory, relativeDirectory)
      : outputDirectory;
    for (const entry of await readdir(absolute, { withFileTypes: true })) {
      const relativePath = relativeDirectory ? `${relativeDirectory}/${entry.name}` : entry.name;
      if (entry.isDirectory()) await walk(relativePath);
      else if (entry.isFile()) found.push(relativePath);
    }
  };

  await walk('');
  return found.sort();
}

/**
 * The service worker source, with the build's identity and precache list baked in.
 *
 * The strategy is documented inside the generated file rather than only here, because the person
 * who has to reason about a stuck installed application will be reading `dist/sw.js`, not this.
 *
 * @param {{basePath: string, sourceStamp: string, precacheUrls: string[]}} build
 * @returns {string}
 */
function serviceWorkerSource({ basePath, sourceStamp, precacheUrls }) {
  return `/**
 * GENERATED by tools/finish-build.mjs. Do not edit this file; edit that one and rebuild.
 *
 * ## What this worker does, in plain words
 *
 * On install it downloads every file this build emitted and stores them in a cache named after
 * the build. From then on the application starts from that cache, so it opens with no network at
 * all. That is the whole offline story: there is no runtime cache growth, no cleverness, and
 * nothing that behaves differently on the second week than it did on the first.
 *
 * ## The update path — the part that must not be broken
 *
 * A precaching worker has one genuinely nasty failure mode. It can serve the OLD build forever:
 * the publish is correct, the source marker says the right thing, and the installed application
 * on a phone that is never reloaded still shows the previous version. It looks identical to a
 * failed deployment and it can persist indefinitely.
 *
 * Three rules prevent that, and all three are required together:
 *
 * 1. The cache name contains the build's source stamp, so a new build NEVER writes into the old
 *    build's cache. Two builds cannot become mixed.
 * 2. \`skipWaiting()\` on install — the new worker takes over instead of waiting for every tab to
 *    close, which on an installed home-screen application may be never.
 * 3. \`clients.claim()\` plus deleting every cache in THIS APPLICATION'S OWN NAMESPACE that is not
 *    this build's, on activate — the new worker starts answering immediately and the old cache
 *    does not outlive the worker that made it. An orphaned cache is exactly how a stale asset
 *    survives, so the sweep has to reach every cache we have ever written and not only the ones
 *    the CURRENT naming scheme produces. See {@link OUR_CACHE_PREFIX} for why it stops there.
 *
 * Taking over promptly means an open tab can be serving the old build's page while the new
 * worker answers its next request. For this application that is the right trade: it is
 * single-user, it is reopened constantly, and a stuck install is far worse than a reload.
 */

const BUILD_STAMP = ${JSON.stringify(sourceStamp)};
const BASE_PATH = ${JSON.stringify(basePath)};
const CACHE_NAME = \`fit-shell-\${BUILD_STAMP}\`;

/**
 * THE NAMESPACE THIS APPLICATION OWNS, and the boundary of what activate is allowed to delete.
 *
 * CACHE STORAGE IS PER-ORIGIN, NOT PER-PATH, and this origin is shared. The site is published to
 * a project path on a hosting account that serves EVERY project of that account from the SAME
 * origin, so \`caches.keys()\` here returns caches belonging to OTHER SITES THE SAME PERSON HAS
 * PUBLISHED. "Delete everything that is not this build's" would therefore reach into a
 * NEIGHBOURING PROJECT and destroy its offline cache from inside our activate handler —
 * silently, on a phone, with no error raised and nothing naming us as the cause. That is the same
 * species of defect this cleanup exists to prevent, so the sweep is scoped by a prefix WE OWN.
 *
 * \`fit-\` is that prefix. It covers this build's \`fit-shell-<stamp>\` AND any earlier cache of
 * ours under a different naming scheme, which is what makes the cleanup reach the predecessor it
 * exists to replace; and it cannot reach a cache we did not write.
 */
const OUR_CACHE_PREFIX = 'fit-';

/** Written by the build from the files it actually emitted, so the list cannot drift. */
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

/** Offline navigation resolves to the single page; routing happens in the fragment. */
const APPLICATION_SHELL_URL = \`\${BASE_PATH}index.html\`;

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      // Reload bypasses the HTTP cache: a precache populated from a stale HTTP response would
      // pin the old build inside the new build's cache, which is the failure this design exists
      // to prevent.
      await cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' })));
      await self.skipWaiting();
    })().catch((error) => {
      // Let the install FAIL loudly rather than activating a worker with a half-filled cache,
      // which would serve a partly-offline application and be far harder to diagnose.
      console.error('[sw] precache failed; this build will not activate', error);
      throw error;
    }),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith(OUR_CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })().catch((error) => {
      console.error('[sw] activation cleanup failed; a previous build cache may survive', error);
      throw error;
    }),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Cross-origin traffic is never cached and never intercepted. Google's endpoints in particular
  // must always be answered by the network or fail honestly; a cached authentication or sync
  // response would be a correctness bug, not an optimisation.
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cached = await caches.match(APPLICATION_SHELL_URL, { cacheName: CACHE_NAME });
        if (cached) return cached;
        try {
          return await fetch(request);
        } catch (error) {
          console.error('[sw] no cached shell and the network is unavailable', error);
          throw error;
        }
      })(),
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { cacheName: CACHE_NAME });
      if (cached) return cached;
      // Not part of this build: pass it through untouched rather than caching it. The cache holds
      // exactly one build's files and nothing else, which is what makes cleanup on activate a
      // complete cleanup.
      return fetch(request);
    })(),
  );
});
`;
}

async function main() {
  const outputDirectory = path.join(applicationRoot, OUTPUT_DIRECTORY);
  const basePath = BASE_PATH;

  const [{ stamp, fileCount }, packageJson] = await Promise.all([
    computeSourceStamp(),
    readFile(path.join(applicationRoot, 'package.json'), 'utf8').then(JSON.parse),
  ]);

  // Read the bundler's record BEFORE listing the output, then remove it: the manifest is a
  // build-time input to this step and has no business in a published artefact, and leaving it in
  // place would also put it in the precache list. Removing it here keeps the emitted set exactly
  // the files the site actually serves.
  const { entryFile, manifestPath } = await readEmittedEntry(outputDirectory);
  await rm(path.join(outputDirectory, '.vite'), { recursive: true, force: true });

  const emitted = await listEmittedFiles(outputDirectory);

  // The entry the bundler says it emitted must actually be on disk and must actually be in the
  // precache set. This is the assertion the old markup-matching version could not make: it
  // inferred a path from rendered output, so it had nothing independent to check itself against.
  if (!emitted.includes(entryFile)) {
    throw new Error(
      `the bundler recorded its entry chunk as "${entryFile}" but no such file was emitted under ` +
        `${OUTPUT_DIRECTORY}/. Refusing to write a precache list that omits the application itself.`,
    );
  }

  // Listed before this step wrote them, so the two files produced HERE are added by name. The
  // worker is excluded on purpose: a cached service worker is how an old worker outlives its
  // build, which is precisely the stuck-installation failure the update strategy exists to
  // prevent. The build record is included so the running application can identify itself offline.
  const precacheUrls = [
    basePath,
    ...emitted.filter((file) => !NEVER_PRECACHED.includes(file)).map((file) => `${basePath}${file}`),
    `${basePath}${BUILD_INFO_FILE}`,
  ];

  if (!precacheUrls.includes(`${basePath}${entryFile}`)) {
    throw new Error(`the precache list does not contain the entry chunk "${entryFile}"`);
  }

  const buildInfo = {
    sourceStamp: stamp,
    sourceFileCount: fileCount,
    builtAt: new Date().toISOString(),
    application: packageJson.name,
    version: packageJson.version,
    basePath,
    outputDirectory: OUTPUT_DIRECTORY,
    // Recorded so an outside step can name the file the application actually starts from without
    // having to read and interpret the built markup, which is the mistake this build just removed.
    entryModule: entryFile,
    emittedFiles: emitted,
    note:
      'sourceStamp is a hash of the source this artefact was built from. Run `npm run check:stale` ' +
      'to compare it against the working tree; a mismatch means dist/ is older than src/.',
  };

  await writeFile(
    path.join(outputDirectory, BUILD_INFO_FILE),
    `${JSON.stringify(buildInfo, null, 2)}\n`,
    'utf8',
  );

  await writeFile(
    path.join(outputDirectory, SERVICE_WORKER_FILE),
    serviceWorkerSource({ basePath, sourceStamp: stamp, precacheUrls }),
    'utf8',
  );

  console.log(`build stamp ${stamp} over ${fileCount} source files`);
  console.log(`output directory ${OUTPUT_DIRECTORY}/ (named once in tools/build-config.mjs)`);
  console.log(`entry module ${entryFile} read from ${path.relative(outputDirectory, manifestPath)}`);
  console.log(`precaching ${precacheUrls.length} urls under ${basePath}`);
}

/**
 * THE EMITTED MODULE ENTRY, READ FROM THE BUNDLER'S OWN RECORD.
 *
 * This function used to pattern-match the built HTML with a regular expression, hunting for a
 * `<script type="module" src="…">` and slicing the path apart to recover the base. That was
 * REPLACED rather than approved, and the reason is the shape of its failure, not its tidiness.
 *
 * A regular expression over generated markup is a guess about the emitted SHAPE. The bundler is
 * free to change that shape in a routine upgrade — a differently ordered attribute, a module
 * preload, an inlined chunk — and when it does, the pattern does not throw at the changed line.
 * It matches something else, or nothing, and the build carries on. The precache list would then
 * be written WITHOUT the application's own entry chunk in it: the service worker installs, every
 * check passes, and the installed application fails to start with no network because the one file
 * it cannot do without was never cached. The same family this build has met repeatedly — an
 * absence that looks exactly like a pass.
 *
 * The bundler already reports what it emitted, structurally, in its manifest: which chunk is the
 * entry, and what it was actually named after content hashing. Reading the entry from there
 * cannot drift, because it is the producer's own account of its output rather than a reader's
 * inference from the producer's rendered result. Note the fix is NOT a better pattern — a
 * differently shaped pattern is the same bet with different odds.
 *
 * The base path is not recovered here at all any more; it is named once in `build-config.mjs`
 * alongside the output directory, and the entry read here is checked AGAINST it, so a disagreement
 * between the configured base and the built artefact is caught rather than papered over.
 *
 * @param {string} outputDirectory
 * @returns {Promise<{entryFile: string, manifestPath: string}>} entryFile is relative to the output
 */
async function readEmittedEntry(outputDirectory) {
  const manifestPath = path.join(outputDirectory, BUNDLER_MANIFEST_FILE);

  let manifest;
  try {
    manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') {
      throw new Error(
        `the bundler manifest is missing at ${BUNDLER_MANIFEST_FILE}. This step runs as the second ` +
          'half of `npm run build` and reads what the bundler recorded; run the whole build rather ' +
          'than this step alone, and check that `build.manifest` is still enabled in vite.config.ts.',
      );
    }
    throw error;
  }

  const entries = Object.values(manifest).filter((chunk) => chunk.isEntry === true);
  if (entries.length !== 1) {
    // Not a guess we may make. Zero means the manifest is not what we think it is; more than one
    // means the application grew a second entry point and the precache and the service worker both
    // need a deliberate decision rather than whichever one sorted first.
    throw new Error(
      `expected exactly one entry chunk in ${BUNDLER_MANIFEST_FILE}, found ${entries.length}: ` +
        `${entries.map((chunk) => chunk.file).join(', ') || '(none)'}`,
    );
  }

  return { entryFile: entries[0].file, manifestPath };
}

main().catch((error) => {
  console.error('post-build step failed:', error);
  process.exitCode = 1;
});
